from datetime import datetime
from fpdf import FPDF


class _PDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(26, 58, 92)  # #1a3a5c
        self.cell(0, 8, "Strata Engineering", align="L")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(74, 127, 165)  # #4a7fa5
        self.cell(0, 8, "Knowledge Assistant - Session Export", align="R")
        self.ln(4)
        self.set_draw_color(208, 228, 240)
        self.set_line_width(0.4)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-13)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 6,
            "This document was generated by Strata Engineering Knowledge Assistant. "
            "It does not replace formal engineering review or sign-off.",
            align="C")
        self.set_text_color(150, 150, 150)
        self.cell(0, 6, f"Page {self.page_no()}", align="R")


def _clean(text: str) -> str:
    """Strip markdown formatting for plain-text PDF output."""
    import re
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)   # bold
    text = re.sub(r"\*(.*?)\*", r"\1", text)         # italic
    text = re.sub(r"#{1,6}\s*", "", text)            # headings
    text = re.sub(r"`{1,3}(.*?)`{1,3}", r"\1", text, flags=re.DOTALL)
    return text.strip()


def generate_pdf(messages: list, report_name: str | None = None) -> bytes:
    pdf = _PDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # Meta info
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, f"Exported: {datetime.now().strftime('%B %d, %Y at %H:%M')}", align="L")
    if report_name:
        pdf.cell(0, 5, f"Report context: {report_name}", align="R")
    pdf.ln(8)

    # Disclaimer box
    pdf.set_fill_color(240, 248, 255)
    pdf.set_draw_color(74, 127, 165)
    pdf.set_line_width(0.3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(74, 127, 165)
    pdf.multi_cell(0, 5,
        "This Q&A session was generated using AI-assisted building science knowledge. "
        "Content should be reviewed by a qualified engineer before being used for "
        "formal recommendations, legal purposes, or strata council decisions.",
        border=1, fill=True)
    pdf.ln(6)

    for msg in messages:
        role = msg.get("role", "")
        content = _clean(msg.get("content", ""))
        sources = msg.get("sources", [])

        if role == "user":
            # Question block
            pdf.set_fill_color(245, 245, 245)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(26, 58, 92)
            pdf.cell(0, 6, "Project Manager", fill=True)
            pdf.ln(1)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 5, content)
            pdf.ln(3)

        elif role == "assistant":
            # Answer block
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(74, 127, 165)
            pdf.cell(0, 6, "Strata Engineering Assistant")
            pdf.ln(1)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 5, content)

            if sources:
                pdf.ln(1)
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(120, 120, 120)
                pdf.cell(0, 4, "Sources: " + " | ".join(sources))
            pdf.ln(5)

            # Divider between exchanges
            pdf.set_draw_color(220, 220, 220)
            pdf.set_line_width(0.2)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(4)

    return bytes(pdf.output())
